insta/insta/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('myapp.urls')),
]
if settings.DEBUG and not settings.USE_CLOUDINARY:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

insta/myapp/urls.py
from django.urls import path, include
from django.contrib.auth import views as auth_views

from . import views


urlpatterns = [
    path('', views.HomeView.as_view() , name = 'home'),
    path('register', views.RegisterView.as_view(), name = 'register'),
    path('sent_email', views.RegisterView.as_view(), name = 'sent_email'),
    path('profile/edit', views.EditProfileView.as_view(), name = 'edit_profile'),
    path('feed/', views.FeedView.as_view(), name = 'feed'),
    path('sub_feed/', views.SubFeedView.as_view(), name='sub_feed'),
    path('post', views.PostingView.as_view(), name = 'post'),
    path('activate/<uidb64>/<token>/', views.ActivateAccount.as_view(), name = 'activate_account'),
    path('login/', views.LoginView.as_view(), name = 'login'),
    path('logout/', auth_views.LogoutView.as_view(next_page='login'), name = 'logout'),
    path('profile/<str:username>/', views.ProfileView.as_view(), name = 'profile'),
    path('profile/', views.ProfileView.as_view(), name = 'profile'),
    path('like_post/<int:post_id>/', views.LikePostView.as_view(), name = 'like_post'),
    #password reset logic:
    path('password-reset/', auth_views.PasswordResetView.as_view(template_name='myapp/password_reset.html'),
         name='password_reset'),
    path('password-reset/done/',
         auth_views.PasswordResetDoneView.as_view(template_name='myapp/password_reset_done.html'),
         name='password_reset_done'),
    path('reset/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(template_name='myapp/password_reset_confirm.html'),
         name='password_reset_confirm'),
    path('reset/done/',
         auth_views.PasswordResetCompleteView.as_view(template_name='myapp/password_reset_complete.html'),
         name='password_reset_complete'),
    #google authorization logic:
    path('accounts/', include('allauth.urls')),
]

insta/myapp/models.py
import logging
from django.db import models
from django.contrib.auth.models import User
from cloudinary.models import CloudinaryField

logger = logging.getLogger(__name__)

class ProfileModel(models.Model):
    user = models.OneToOneField(User, on_delete = models.CASCADE, related_name = 'profile')
    first_name = models.CharField(max_length = 20, blank = True)
    last_name = models.CharField(max_length = 20, blank = True)
    GENDER_CHOICES = [
        ('male', 'Male'),
        ('female', 'Female'),
        ('other', 'Other'),
    ]
    gender = models.CharField(max_length = 6, choices = GENDER_CHOICES, default = 'male')
    avatar = CloudinaryField('avatars', blank = True)
    birth_date = models.DateField(blank = True, null = True)
    bio = models.TextField(blank = True, null = True)
    subscribers = models.ManyToManyField(User, related_name='subscribed', blank=True)

    objects = models.Manager()

    def __str__(self):
        return f"Profile of {self.user.username}"

    class Meta:
        app_label = 'myapp'


class PostModel(models.Model):
    author = models.ForeignKey(User, on_delete = models.CASCADE, related_name = 'post')
    text = models.TextField(blank = True)
    created_at = models.DateTimeField(auto_now_add = True)
    tags = models.ManyToManyField('TagModel', related_name = 'posts', blank = True)
    likes = models.ManyToManyField(User, related_name = 'liked_posts', blank = True)

    objects = models.Manager()

    def clean(self):
        if not self.text and not self.images:
            logger.warning(f"User {self.author} attempted to create an empty post.")
            print("❌ Error: Cannot create an empty post!")
            # No `raise ValidationError()` to avoid crashing the page

    def save(self, *args, **kwargs):
        self.full_clean()
        super().save(*args, **kwargs)

    def __str__(self):
        return (f"Post by {self.author.username}:"
                f" {'Text and image post' if self.text and self.images else 'Simple post'}")


class TagModel(models.Model):
    name = models.CharField(max_length = 50, unique = True)

    def __str__(self):
        return f'{self.name}'

class PostImage(models.Model):
    post = models.ForeignKey(PostModel, on_delete = models.CASCADE, related_name = 'images')
    image = CloudinaryField('image')

    def __str__(self):
        return f'Image for {self.post.author.username}' if self.post else "Orphaned Image"

insta/myapp/forms.py
from django import forms
from django_select2.forms import Select2MultipleWidget
from django.forms import inlineformset_factory

from .models import ProfileModel, PostModel, PostImage, User

class RegistrationForm(forms.Form):
    username = forms.CharField(max_length=20)
    email = forms.EmailField()
    password = forms.CharField(
        label = "Password",
        widget =  forms.PasswordInput,
    )
    confirm_password = forms.CharField(
        label = "Confirm Password",
        widget = forms.PasswordInput
    )

#validaion
    def clean(self):
        cleaned_data = super().clean()
        password = cleaned_data.get("password")
        confirm_password = cleaned_data.get("confirm_password")
        username = cleaned_data.get("username")
        email = cleaned_data.get("email")

        if password != confirm_password:
            raise forms.ValidationError("Passwords do not match")

        if username:
            User.objects.filter(username=username, is_active=False).delete()
        if email:
            User.objects.filter(email=email, is_active=False).delete()
        return cleaned_data

    def clean_email(self):
        email = self.cleaned_data['email']
        if User.objects.filter(email=email).exists():
            raise forms.ValidationError('User with this email already exists')
        return email


class EditProfileForm(forms.ModelForm):
    class Meta:
        model = ProfileModel
        fields = ['first_name', 'last_name', 'gender', 'avatar', 'birth_date', 'bio']
        gender = forms.ChoiceField(choices = model.GENDER_CHOICES)
        birth_date = forms.DateField(
            widget=forms.DateInput(attrs={'type': 'date'})
        )

    def __str__(self):
        return f"{self.cleaned_data.get('first_name', '')} {self.cleaned_data.get('last_name', '')}"


class LoginForm(forms.Form):
    username = forms.CharField(widget = forms.TextInput())
    password = forms.CharField(widget = forms.PasswordInput())
    remember = forms.BooleanField(required = False)


class PostForm(forms.ModelForm):
    class Meta:
        model = PostModel
        fields = ['text', 'tags']

        def __init__(self, *args, **kwargs):
            super().__init__(*args, **kwargs)
            self.fields['tags'].widget.attrs.update({
                'class': 'select2-chips',  # ← добавляем класс для Select2
                'multiple': 'multiple',  # если это multiple select
            })


class PostImageForm(forms.ModelForm):
    class Meta:
        model = PostImage
        fields = ['image']

PostImageFormSet = inlineformset_factory(PostModel, PostImage, form = PostImageForm, extra = 3, can_delete = False)

class RestorePasswordForm(forms.Form):
    username = forms.CharField(label='username', max_length=100)
    email = forms.EmailField(label='Email')

insta/myapp/views.py
import logging
from django.contrib.auth import login, authenticate, logout
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.models import User
from django.contrib.auth.tokens import default_token_generator
from django.db import IntegrityError
from django.http import HttpResponse, JsonResponse
from django.shortcuts import render, redirect, get_object_or_404
from django.utils.decorators import method_decorator
from django.utils.http import urlsafe_base64_decode
from django.views import View
from django.views.decorators.http import require_POST
from django.views.generic import TemplateView
from django.core.files.storage import default_storage
from cloudinary_storage.storage import MediaCloudinaryStorage

from .forms import RegistrationForm, EditProfileForm, LoginForm, PostForm, PostImageFormSet
from .models import PostModel, ProfileModel
from .services import send_activation_email, generate_activation_link

logger = logging.getLogger(__name__)

class HomeView(TemplateView):
    template_name = 'myapp/home.html'


class RegisterView(View):
    def get(self, request):
        if request.user.is_authenticated:
            logout(request)
        form = RegistrationForm()
        return render(request, 'myapp/registration.html', {'form': form})

    def post(self, request):
        if request.user.is_authenticated:
            logout(request)
        form = RegistrationForm(request.POST)

        if form.is_valid():
            username = form.cleaned_data['username']
            email = form.cleaned_data['email']
            password = form.cleaned_data['password']
            try:
                user = User.objects.create(username = username, email = email, is_active = False)
                user.set_password(password)
                user.save()

                activation_link = generate_activation_link(user)
                send_activation_email(user, activation_link)
                return render(request, 'myapp/sent_email.html')
            except IntegrityError:
                form.add_error('username', 'A user with this username is already registered')
                return render(request, 'myapp/registration.html', {'form':form})
        return render(request, 'myapp/registration.html', {'form': form})


class ActivateAccount(View):
    def get(self, request, uidb64, token):
        try:
            uid = urlsafe_base64_decode(uidb64).decode()
            user = User.objects.get(pk = uid)
        except (TypeError, ValueError, OverflowError, User.DoesNotExist):
            return render(request, 'myapp/activation.html',
                          {'message': 'The activation link is invalid or expired.'})

        if user is not None and default_token_generator.check_token(user, token):
            user.is_active = True
            user.save()
            return render(request, 'myapp/activation.html',
                          {'message': '🎉Activation completed🎉'})
        else:
            return render(request, 'myapp/activation.html',
                          {'message': 'The activation link is invalid.'})


class EditProfileView(LoginRequiredMixin, View):
    def get(self, request):
        form = EditProfileForm(instance = request.user.profile)
        return render(request, 'myapp/edit_profile.html', {'form': form})

    def post(self, request):
        form = EditProfileForm(request.POST,request.FILES, instance=request.user.profile)
        if form.is_valid():
            form.save()
            return redirect('profile')
        else:
            return render(request, 'myapp/edit_profile.html', {'form': form})


class LoginView(View):
    def get(self, request):
        if request.user.is_authenticated:
            logout(request)
            return redirect(request.GET.get('next', request.META.get('HTTP_REFERER', 'login')))
        form = LoginForm()
        return render(request, 'myapp/login.html', {'form': form})

    def post(self, request):
        if request.user.is_authenticated:
            logout(request)

        form = LoginForm(request.POST)
        if not form.is_valid():
            print('Form errors:', form.errors)
            return render(request, 'myapp/login.html', {'form': form})

        user = authenticate(
            username = form.cleaned_data['username'],
            password = form.cleaned_data['password']
        )
        if user is None:
            print('Authentication failed:', user)
            form.add_error(None, 'Invalid login credentials')
            return render(request, 'myapp/login.html', {'form': form})

        login(request, user)

        next_url = request.POST.get('next')

        return redirect(next_url if next_url else 'feed')


class FeedView(LoginRequiredMixin, View):
    def get(self, request):
        posts = PostModel.objects.all().order_by("-created_at")
        return render(request, 'myapp/feed.html', {'posts': posts})

class SubFeedView(LoginRequiredMixin, View):
    def get(self, request):
        user = request.user
        subscribed_profiles = user.subscribed.all()  # Это ProfileModel
        subscribed_users = [profile.user for profile in subscribed_profiles]

        posts = PostModel.objects.filter(author__in=subscribed_users).order_by('-created_at')
        return render(request, 'myapp/sub_feed.html',{'posts': posts})


class PostingView(LoginRequiredMixin, View):
    def get(self, request):
        form = PostForm()
        formset = PostImageFormSet()
        return render(request, 'myapp/new_post.html', {'form': form, 'formset': formset})

    def post(self, request):
            post_form = PostForm(request.POST)
            formset = PostImageFormSet(request.POST, request.FILES)

            if post_form.is_valid() and formset.is_valid():
                post = post_form.save(commit = False)
                post.author = request.user
                post.save()
                post_form.save_m2m()

                cloud_storage = MediaCloudinaryStorage()
                images = formset.save(commit = False)
                for image in images:
                    image.post = post
                    with image.image.open() as f:
                        image.image = cloud_storage.save(image.image.name, f)
                    image.save()

                return redirect('profile')
            else:
                return render(request, 'myapp/new_post.html',
                              {'form': post_form, 'formset' : formset})


class ProfileView(LoginRequiredMixin, View):
    def get(self, request, username = None):
        # Here it is decided whose page will be opened, the current user or another
        if username:
            profile_owner = get_object_or_404(User, username = username)
        elif request.user.is_authenticated:
            profile_owner = request.user
        else:
            return HttpResponse("The user is not authorized", status = 401)

        is_own_profile = request.user.is_authenticated and request.user == profile_owner

        profile = get_object_or_404(ProfileModel, user = profile_owner)
        is_subscribed = request.user in profile.subscribers.all()
        posts = PostModel.objects.filter(author = profile_owner).order_by("-created_at")
        return render(request, 'myapp/profile.html', {'profile_owner': profile_owner,
                                                               'posts': posts,
                                                               'is_own_profile': is_own_profile,
                                                               'is_subscribed': is_subscribed,})

    def post(self, request, username = None):
        if username:
            profile_owner = get_object_or_404(User, username = username)
        elif request.user.is_authenticated:
            profile_owner = request.user
        else:
            return HttpResponse("The user is not authorized", status = 401)

        profile = profile_owner.profile

        if request.user == profile_owner:
            # cannot subscribe to yourself, do nothing
            return JsonResponse({"error": "Cannot subscribe to yourself"}, status = 400)
        else:
            if profile.subscribers.filter(id=request.user.id).exists():
                profile.subscribers.remove(request.user)
                is_subscribed = False
            else:
                profile.subscribers.add(request.user)
                is_subscribed = True

        return JsonResponse({"is_subscribed": is_subscribed})

# class ProfileView(LoginRequiredMixin, View):
#     @method_decorator(require_POST)
#     def post(self, request, username = None):
#         profile_owner = get_object_or_404(User, username = username)


class LikePostView(LoginRequiredMixin, View):
    @method_decorator(require_POST)
    def post(self, request, post_id):
        post = get_object_or_404(PostModel, id = post_id)
        if request.user in post.likes.all():
            post.likes.remove(request.user)
        else:
            post.likes.add(request.user)
        return JsonResponse({'likes_count': post.likes.count()})

class RestorePasswordView(View):
    def get(self, request):
        if request.user.is_authenticated:
            logout(request)

        return render(request, 'myapp/restore_profile.html')

insta/myapp/templates/myapp/Registration.html
<!DOCTYPE html>
<!-- Coding By CodingNepal - www.codingnepalweb.com -->
<html>
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Registration</title>
  {% load static %}
  <link href="{% static 'styles.css' %}" rel="stylesheet">
</head>
<body>
  <div class="wrapper">
    <form method="POST" id="registration-form">
      <h2>Registration</h2>
      {% csrf_token %}

      <!-- username -->
      <div class="input-field">
        <input type="text" name="username" id="id_username" class="custom-style" required>
        <label>Enter username</label>
      </div>

      <!-- Email -->
      <div class="input-field">
        <input type="email" name="email" id="id_email" class="custom-style"
               pattern="[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}"
               title="Email must be in the format: example@domain.com"
               required>
        <label>Enter your email</label>
      </div>

      <!-- Create Password -->
      <div class="input-field">
        <input type="password" name="password" id="id_password" class="custom-style" minlength="6" required>
        <label>Create your password</label>
      </div>

      <!-- Confirm Password -->
      <div class="input-field">
        <input type="password" name="confirm_password" id="id_confirm_password" class="custom-style" minlength="6" required>
        <label>Confirm your password</label>
      </div>
      <div id="passwordError" style="color: red;"></div>

      <!-- Submit Button -->
      <button type="submit">Register</button>

      <!-- Register link (if the user already has an account) -->
      <div class="register">
        <p>Already have an account? <a href="{% url 'login' %}">Login</a></p>
      </div>
    </form>
  </div>
  <script src="{% static 'script.js' %}"></script>
  </script>
</body>
</html>

insta/myapp/templates/myapp/activation.html
{% extends 'myapp/base.html' %}

{% block title %}Account activation{% endblock %}
{% block show_nav %}{% endblock %}

{% block content %}
    <h2>{{ message }}</h2>
    <meta http-equiv="refresh" content="4; url = /login/?next=/profile/edit">
    <h2>You will be redirected to the login page within 3 seconds.</h2>
{% endblock %}

insta/myapp/templates/myapp/edit_profile.html
{% extends 'myapp/base.html' %}

{% block title %}Edit profile{% endblock %}

{% block extra_css %}
{% load static %}
<link href="{% static 'edit_profile.css' %}" rel="stylesheet">
{% endblock %}

{% block navigation %}
<li><button class="white-btn" onclick="location.href='/profile'">PROFILE</button></li>
{% endblock %}

{% block content %}
<div class="wrapper">
  <form class="edit_form" method="POST" enctype="multipart/form-data">
    {% csrf_token %}

    <div class="input-field">
      <label for="id_first_name">First Name:</label>
      {{ form.first_name }}
      {% if form.first_name.errors %}
      <ul>
        {% for error in form.first_name.errors %}
        <li>{{ error }}</li>
        {% endfor %}
      </ul>
      {% endif %}
    </div>

    <div class="input-field">
      <label for="id_last_name">Last Name:</label>
      {{ form.last_name }}
      {% if form.last_name.errors %}
      <ul>
        {% for error in form.last_name.errors %}
        <li>{{ error }}</li>
        {% endfor %}
      </ul>
      {% endif %}
    </div>

    <div class="input-field">
      <label for="id_gender">Gender:</label>
      {{ form.gender }}
      {% if form.gender.errors %}
      <ul>
        {% for error in form.gender.errors %}
        <li>{{ error }}</li>
        {% endfor %}
      </ul>
      {% endif %}
      <br></br>
    </div>

    <div class="input-field">
      <label for="id_avatar">Avatar:</label>
      {{ form.avatar }}
      {% if form.avatar.errors %}
      <ul>
        {% for error in form.avatar.errors %}
        <li>{{ error }}</li>
        {% endfor %}
      </ul>
      {% endif %}
      <br></br>
    </div>

    <div class="input-field">
      <label for="id_bio">Bio:</label>
      {{ form.bio }}
      {% if form.bio.errors %}
      <ul>
        {% for error in form.bio.errors %}
        <li>{{ error }}</li>
        {% endfor %}
      </ul>
      {% endif %}
    </div>

    <div>
      <label for="id_birth_date">Birth date:</label>
      <input type="date" name="birth_date" id="id_birth_date" value="{{ form.birth_date.value }}">
      {% if form.birth_date.errors %}
      <ul>
        {% for error in form.birth_date.errors %}
        <li>{{ error }}</li>
        {% endfor %}
      </ul>
      {% endif %}
    </div>

    <button class="submit_button" type="submit">Save changes</button>
  </form>
</div>
</body>
{% endblock %}

insta/myapp/templates/myapp/feed.html
{% extends 'myapp/base.html' %}

{% block title%}Feed{% endblock %}

{% block extra_css%}
    {% load static %}
    <link href="{% static 'profile-feed.css' %}" rel="stylesheet">
{% endblock %}

{% block navigation %}

  <li><button class="white-btn" onclick="location.href='/profile'">PROFILE</button></li>

{% endblock %}

{% block content %}
<div class="feed_wrapper">
  <div class="feed_post_container">
      {% for post in posts %}
          <div class="post">
              <div class="post-author">
                  <a href="/profile/{{ post.author.username }}" class="author-avatar">
                    {% if post.author.profile.avatar %}
					    <img src="{{ post.author.profile.avatar.url }}" alt="Avatar">
				    {% else %}
					    <img src="https://res.cloudinary.com/dnctmhqcl/image/upload/default_avatar_gruuhe" alt="Default Avatar">
				    {% endif %}
                  </a>
                  <a href="/profile/{{ post.author.username }}" class="author-name">{{ post.author.username }}</a>
              </div>
              <p>{{ post.text }}</p>
          <div>
          <div class="tags-container">
                {% for tag in post.tags.all %}
                    <span><a href="">{{ tag.name }}</a></span>
                {% empty %}
                    <p></p>
                {% endfor %}
          </div>
          </div>
            {% if post.images.all %}

            {% for image in post.images.all %}
                <img src="{{ image.image.url }}" alt="Post Image" loading="lazy" />
            {% endfor %}
            {% endif %}
              <div class="post-footer">
                  <p>{{ post.created_at }}</p>
                  <div class="like-button-container">
                      <div id="like-button-{{ post.id }}" style="width:40px; height:40px; cursor:pointer;"></div>
                      <a href="#" class="likes-count" onclick="showLikes({{ post.id }})">{{ post.likes.count }}</a>
                  </div>
              </div>
          </div>
      {% endfor %}
  </div>
</div>
{% endblock %}

insta/myapp/templates/myapp/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Welcome</title>
    {% load static %}
    <link href="{% static 'styles.css' %}" rel="stylesheet">
    <link href="{% static 'styles_home.css' %}" rel="stylesheet">
</head>
<body>
    <div class="welcome-container">
        <div class="welcome-box">
            <h1>WELCOME TO JANGOGRAMM</h1>
            <h2>Register or login:</h2>
            <br></br>
            <div class="button-container">
                <a href="{% url 'login' %}" class="login-btn">Login</a>
                <a href="{% url 'register' %}" class="register-btn">Register</a>
            </div>
        </div>
    </div>
</body>
</html>

insta/myapp/templates/myapp/new_post.html
{% extends 'myapp/base.html' %}
{% load widget_tweaks %}

{% block title %}New post{% endblock %}



{% block extra_css %}
    {% load static %}
    <link href="{% static 'new_post.css' %}" rel="stylesheet" />
{% endblock %}

{% block navigation %}

  <li><button class="white-btn" onclick="location.href='/profile'">PROFILE</button></li>

{% endblock %}

{% block content %}

<div class="wrapper">
  <div class="posts-container">
        <h2>Make new post</h2>
       <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="input-field">
              <label for="id_text">Post text:</label>
              {{ form.text|attr:"placeholder: write your story here" }}
              {% if form.text.errors %}
              <ul>
                {% for error in form.text.errors %}
                <li>{{ error }}</li>
                {% endfor %}
              </ul>
              {% endif %}
            </div>
            <div class="input-field">
                <label for="tags">Post tags:</label>
                {{ form.tags }}
                {% if form.tags.errors %}
                <ul>
                    {% for error in form.tags.errors %}
                    <li>{{ error }}</li>
                    {% endfor %}
                </ul>
                {% endif %}
            </div>
            {% if form.errors %}
                <div class="errorlist">
                    {{ form.errors }}
                </div>
            {% endif %}

            <h3>Add ap to 3 images</h3>

            {{ formset.management_form }}
            {% for form in formset %}
                {{ form.as_p }}
            {% endfor %}

            <button type="submit">CREATE POST</button>
        </form>
    </div>
 </div>
{% endblock %}

insta/myapp/templates/myapp/password_reset.html
{% extends 'myapp/base.html' %}
{% block content %}
  {% block show_nav %}
  {% endblock %}
  <h2>RESET PASSWORD</h2>
  <br>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Send lik</button>
  </form>
{% endblock %}

insta/myapp/templates/myapp/password_reset_complete.html
{% extends 'myapp/base.html' %}
{% block content %}
      {% block show_nav %}
      {% endblock %}
    <meta http-equiv="refresh" content="7; url = /login/?next=/profile">
    <h2>DONE, NOW YOU WILL BE REDIRECTED TO LOGIN PAGE WITHIN 5 SECONDS</h2>
{% endblock %}

insta/myapp/templates/myapp/password_reset_confirm.html
{% extends 'myapp/base.html' %}
{% block content %}
  {% block show_nav %}
  {% endblock %}
  <h2>ENTER NEW PASSWORD</h2>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">SUBMIT</button>
  </form>
{% endblock %}

insta/myapp/templates/myapp/password_reset_done.html
{% extends 'myapp/base.html' %}
{% block content %}
  {% block show_nav %}
  {% endblock %}
  <a href="https://mail.google.com" class="btn btn-primary">A link to reset your password has been sent to your email</a>
{% endblock %}

insta/myapp/templates/myapp/registration.html
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Registration</title>
  {% load static %}
  <link href="{% static 'styles.css' %}" rel="stylesheet">
  <link href="{% static 'registration.css' %}" rel="stylesheet">
</head>
<body>
  <div class="wrapper">
    <form method="POST" id = "registration-form">
      <h2>Registration</h2>
      {% csrf_token %}

      {% if form.non_field_errors %}
      <ul class="errorlist">
          {% for error in form.non_field_errors %}
              <li>{{ error }}</li>
          {% endfor %}
      </ul>
      {% endif %}
      <!-- username -->
      <div class="input-field">
        {% if form.username.errors %}
          <div class="error">
              {% for error in form.username.errors %}
                  <p>{{ error }}</p>
              {% endfor %}
          </div>
        {% endif %}
        <label>Enter username</label>
        <input type = "text" name = "username" id = "id_username" class = "custom-style" required>
      </div>
      <!-- Email -->
      <div class="input-field">
        {% if form.email.errors %}
          <div class="error">
              {% for error in form.email.errors %}
                  <p>{{ error }}</p>
              {% endfor %}
          </div>
        {% endif %}
        <label>Enter your email</label>
        <input type = "email" name = "email" id = "id_email" class = "custom-style"
               pattern="[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}"
               title="Email must be in the format: example@domain.com"
               required>
      </div>

      <!-- Create Password -->
      <div class="input-field">
        <label>Create your password</label>
        <input type="password" name="password" id="id_password" class="custom-style" minlength="6" required>
      </div>

      <!-- Confirm Password -->
      <div class="input-field">
        <label>Confirm your password</label>
        <input type="password" name="confirm_password" id="id_confirm_password" class="custom-style" minlength="6" required>
      </div>
      <div id="passwordError" style="color: red;"></div>

      <button type="submit">Register</button>

      <!-- Register link (if the user already has an account) -->
      <div class="register">
        <p>Already have an account? <a href="{% url 'login' %}">Login</a></p>
      </div>
    </form>
  </div>
  <script src="{% static 'check_password_match.js' %}"></script>
</body>
</html>

insta/myapp/templates/myapp/sent_email.html
{% extends 'myapp/base.html' %}

{% block title %}Activate your account{% endblock %}
{% block show_nav %}{% endblock %}

{% block content %}
    <a href="https://mail.google.com" class="btn btn-primary">
        We have sent you a link to activate your account by email, please check your inbox.
    </a>
{% endblock %}